---
- hosts: all
  sudo: yes
  
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
    
    - name: Install git
      apt: pkg=git state=present
    
    - name: Clone repo
      git: repo=https://github.com/JPPorcel/CCSA.git dest=/opt/app version=HEAD
      
    - name: Install mongo
      shell: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 && echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list && sudo apt-get update && sudo apt-get install -y mongodb-org && sudo service mongod start"

    - name: Load database
      shell: "cd /opt/app/mongo && mongoimport --db restaurants --collection restaurants --drop --file restaurantes.json"
