---
- hosts: all
  sudo: yes
  
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
    
    - name: Install git
      apt: pkg=git state=present

    - name: Install NodeJS and npm
      apt: name={{ item }} state=present
      with_items:
        - nodejs
        - nodejs-dev
        - nodejs-legacy
        - npm
    
    - name: Install pm2 for manage our nodejs application
      npm:
        name: pm2
        global: yes
    
    - name: Clone repo
      git: repo=https://github.com/JPPorcel/CCSA.git dest=/opt/app version=HEAD
      
    - name: Install dependencies with npm
      shell: "cd /opt/app && sudo npm install"
      
    - name: Run server with pm2
      shell: 'cd /opt/app && pm2 start server.js && pm2 startup'
      
    - name: Install nginx
      apt: pkg=nginx state=present
