---
- hosts: all
  sudo: yes
  
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
    
    - name: Install git
      apt: pkg=git state=present
      
    - name: Install MySQL
      apt: pkg=mysql-server state=present
    
    - name: Clone repo
      git: repo=https://github.com/JPPorcel/CCSA.git dest=/opt/app version=HEAD
      
    - name: Load database
      shell: "cd /opt/app/mysql && mysql < modelo.sql && mysql Music < marchas.sql"
