---
- hosts: all
  sudo: yes
  
  tasks:
    - name: Install git
      yum: name=git state=present
    
    - name: Clone repo
      git: repo=https://github.com/JPPorcel/CCSA.git dest=/opt/app version=HEAD
      
    - name: Install mongo repository
      shell: 'cd /opt/app/provision/ && cp mongodb-org.repo /etc/yum.repos.d/ && yum repolist'
      
    - name: Install mongo
      yum: name=mongodb-org state=present
      
    - name: Start mongod
      shell: 'sudo systemctl start mongod'

    - name: Load database
      shell: "cd /opt/app/mongo && mongoimport --db restaurants --collection restaurants --drop --file restaurantes.json"
      
    - name: Open ports for mongo
      shell: 'iptables -I INPUT -p udp -m udp --dport 27017 -j ACCEPT && iptables -I INPUT -p tcp -m tcp --dport 27017 -j ACCEPT'
